fail_fast: true
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-xml
      - id: check-merge-conflict
  - repo: local
    hooks:
      - id: shellcheck
        name: Run static analysis (shellcheck)
        entry: shellcheck
        language: system
        files: \.(sh|bash)$
        types: [file]
        args: [ '-x', '-e', 'SC2034' ]
      - id: shfmt
        name: Run lint check (shfmt -d)
        entry: shfmt
        language: system
        files: \.(sh|bash)$
        types: [file]
        args: [ '-i', '0', '-ci', '-sr', '-d' ]
      - id: shfmtw
        name: Auto-fix lint errors (shfmt -w)
        entry: shfmt
        language: system
        stages: [manual]
        files: \.(sh|bash)$
        types: [file]
        args: [ '-i', '0', '-ci', '-sr', '-kp', '-w' ]
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-beta.5
    hooks:
      - id: golangci-lint-mod
        args: ["--allow-parallel-runners"]
      - id: go-build-repo-mod
      - id: go-mod-tidy
      - id: go-mod-tidy-repo
      - id: go-vet-mod
      - id: go-fmt
